/* tslint:disable */
/* eslint-disable */
/**
 * Mafiasi Kulturgenießer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AG
 */
export interface AG {
    /**
     *
     * @type {string}
     * @memberof AG
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof AG
     */
    name: string;
    /**
     *
     * @type {Array<string>}
     * @memberof AG
     */
    readonly openProposals: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof AG
     */
    readonly viewings: Array<string>;
}

/**
 * Check if a given object implements the AG interface.
 */
export function instanceOfAG(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "openProposals" in value;
    isInstance = isInstance && "viewings" in value;

    return isInstance;
}

export function AGFromJSON(json: any): AG {
    return AGFromJSONTyped(json, false);
}

export function AGFromJSONTyped(json: any, ignoreDiscriminator: boolean): AG {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'openProposals': json['open_proposals'],
        'viewings': json['viewings'],
    };
}

export function AGToJSON(value?: AG | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'name': value.name,
    };
}
