/* tslint:disable */
/* eslint-disable */
/**
 * Mafiasi Kulturgenießer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CastVoteRequest
 */
export interface CastVoteRequest {
    /**
     *
     * @type {number}
     * @memberof CastVoteRequest
     */
    value: number;
}

/**
 * Check if a given object implements the CastVoteRequest interface.
 */
export function instanceOfCastVoteRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function CastVoteRequestFromJSON(json: any): CastVoteRequest {
    return CastVoteRequestFromJSONTyped(json, false);
}

export function CastVoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CastVoteRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'value': json['value'],
    };
}

export function CastVoteRequestToJSON(value?: CastVoteRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'value': value.value,
    };
}
