/* tslint:disable */
/* eslint-disable */
/**
 * Mafiasi Kulturgenießer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Proposal
 */
export interface Proposal {
    /**
     *
     * @type {string}
     * @memberof Proposal
     */
    note: string;
    /**
     *
     * @type {string}
     * @memberof Proposal
     */
    readonly proposedBy: string;
    /**
     *
     * @type {number}
     * @memberof Proposal
     */
    readonly votesCast: number;
    /**
     *
     * @type {number}
     * @memberof Proposal
     */
    readonly voteScore: number;
}

/**
 * Check if a given object implements the Proposal interface.
 */
export function instanceOfProposal(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "note" in value;
    isInstance = isInstance && "proposedBy" in value;
    isInstance = isInstance && "votesCast" in value;
    isInstance = isInstance && "voteScore" in value;

    return isInstance;
}

export function ProposalFromJSON(json: any): Proposal {
    return ProposalFromJSONTyped(json, false);
}

export function ProposalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Proposal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'note': json['note'],
        'proposedBy': json['proposed_by'],
        'votesCast': json['votes_cast'],
        'voteScore': json['vote_score'],
    };
}

export function ProposalToJSON(value?: Proposal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'note': value.note,
    };
}
