/* tslint:disable */
/* eslint-disable */
/**
 * Mafiasi Kulturgenießer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Viewing
 */
export interface Viewing {
    /**
     *
     * @type {Date}
     * @memberof Viewing
     */
    viewedAt: Date;
    /**
     *
     * @type {string}
     * @memberof Viewing
     */
    note: string;
}

/**
 * Check if a given object implements the Viewing interface.
 */
export function instanceOfViewing(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "viewedAt" in value;
    isInstance = isInstance && "note" in value;

    return isInstance;
}

export function ViewingFromJSON(json: any): Viewing {
    return ViewingFromJSONTyped(json, false);
}

export function ViewingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Viewing {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'viewedAt': (new Date(json['viewed_at'])),
        'note': json['note'],
    };
}

export function ViewingToJSON(value?: Viewing | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'viewed_at': (value.viewedAt.toISOString()),
        'note': value.note,
    };
}
