# Generated by Django 4.2.10 on 2024-02-29 19:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mafiasi_kultur_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AG",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Medium",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                (
                    "ag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mediums",
                        to="mafiasi_kultur_core.ag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("note", models.TextField()),
                (
                    "medium",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="mafiasi_kultur_core.medium"
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposed_mediums",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("value", models.IntegerField(choices=[(-1, "dislike"), (0, "don't care"), (1, "like")])),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mafiasi_kultur_core.proposal"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Viewing",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("viewed_at", models.DateTimeField()),
                ("note", models.TextField()),
                (
                    "medium",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="mafiasi_kultur_core.medium"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="proposal",
            name="votes",
            field=models.ManyToManyField(through="mafiasi_kultur_core.Vote", to=settings.AUTH_USER_MODEL),
        ),
    ]
