/* tslint:disable */
/* eslint-disable */
/**
 * Mafiasi Kulturgenießer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AG,
} from '../models/index';
import {
    AGFromJSON,
    AGToJSON,
} from '../models/index';

export interface AgsRetrieveRequest {
    id: string;
}

/**
 *
 */
export class AgsApi extends runtime.BaseAPI {

    /**
     */
    async agsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AG>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/ags/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AGFromJSON));
    }

    /**
     */
    async agsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AG>> {
        const response = await this.agsListRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async agsRetrieveRaw(requestParameters: AgsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AG>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling agsRetrieve.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/ags/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AGFromJSON(jsonValue));
    }

    /**
     */
    async agsRetrieve(requestParameters: AgsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AG> {
        const response = await this.agsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
